export type {
  TraversalPlan,
  TraversalPlanner,
  TraversalPlanningRequest,
  CommitFact,
  CommitOid,
  CommitTraversalExtractor,
  CommitTraversalRequest,
  CoordinatorDependencies,
  CoordinatorRequest,
  CoordinatorResult,
  DiagnosticReporter,
  ExtractionCoordinator,
  ExtractionRange,
  ExtractionResult,
  ExtractionState,
  ExtractorConfig,
  Fact,
  FactFor,
  FactProjector,
  FactType,
  FileChangeExpander,
  FileChangeFact,
  MonotonicClock,
  Namespace,
  OutputSink,
  PersonIdentity,
  PluginEntry,
  PluginFactory,
  PluginFailurePolicy,
  PluginInitResult,
  PluginProjectionResult,
  PluginProjectionValue,
  PluginRuntimeContext,
  ProjectedCommit,
  ProjectedExtensionValue,
  ProjectedExtensions,
  ProjectedFileChange,
  ProjectedPerson,
  ProjectedRecord,
  ProjectedRecordFor,
  ProjectedRepository,
  ProjectionContext,
  ProjectorPlugin,
  ProfilingEntry,
  ProgressEvent,
  ProgressPhase,
  ProgressReporter,
  RefCheckpoint,
  RefType,
  RotationConfig,
  StageProfiler,
  StateStore,
  OidProfile,
  WallClock,
} from "./types.js";
export { assertNever, isCommitOid, isCommitOidForProfile, REF_TYPES } from "./types.js";
export { DefaultTraversalPlanner } from "./traversal-planner.js";
export { DefaultExtractionCoordinator } from "./extraction-coordinator.js";
export { DefaultCommitTraversalExtractor } from "./commit-traversal-extractor.js";
export { DefaultFileChangeExpander } from "./file-change-expander.js";
export { DefaultFactProjector, projectCommit, projectFileChange } from "./fact-projector.js";
export { EnrichingFactProjector } from "./enriching-fact-projector.js";
export { MISSING_STATES } from "./consts.js";
